### ISSUE TITLE
Error when inserting an element into a writable list_of

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/cpp11#130] opened 2020-11-18 17:10 UTC
```r
cpp11::cpp_source(
  code = '
  #include "cpp11/integers.hpp"
  #include "cpp11/list_of.hpp"
  
  [[cpp11::register]]
  cpp11::writable::list_of<cpp11::writable::integers> test() {
    cpp11::writable::integers x({1, 2, 3});
    cpp11::writable::list_of<cpp11::writable::integers> out(1);
    out[0] = x;
    return out;
  }
  '
)

test()
#> Error in test(): Invalid input type, expected 'integer' actual 'NULL'
```

Am I doing something wrong here?

**Comment by DavisVaughan** [comment] 2020-11-18 17:12
This works:

```r
cpp11::cpp_source(
  code = '
  #include "cpp11/integers.hpp"
  #include "cpp11/list_of.hpp"
  
  [[cpp11::register]]
  cpp11::writable::list_of<cpp11::writable::integers> test() {
    cpp11::writable::integers x({1, 2, 3});
    cpp11::writable::list_of<cpp11::writable::integers> out({x});
    //out[0] = x;
    return out;
  }
  '
)

test()
#> [[1]]
#> [1] 1 2 3cpp11::cpp_source(
  code = '
  #include "cpp11/integers.hpp"
  #include "cpp11/list_of.hpp"
  
  [[cpp11::register]]
  cpp11::writable::list_of<cpp11::writable::integers> test() {
    cpp11::writable::integers x({1, 2, 3});
    cpp11::writable::list_of<cpp11::writable::integers> out({x});
    //out[0] = x;
    return out;
  }
  '
)

test()
#> [[1]]
#> [1] 1 2 3
```

**Comment by jimhester** [comment] 2020-12-10 19:19
Basically a duplicate of https://github.com/r-lib/cpp11/issues/129#issuecomment-730415040, reason explained in that comment.

**Closed by jimhester** 2020-12-10 19:19 UTC
